name: Build Windows Desktop

defaults:
  run:
    shell: bash

env:
  CI: true

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - name: Install Python setuptools
        run: pip.exe install setuptools
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'yarn'
      
      - name: Install Yarn
        run: npm install -g yarn
      
      - name: Install dependencies
        run: yarn --immutable
      
      - name: Build Electron App (with translations)
        run: ./bin/package-electron
      
      - name: Upload Windows x64 Installer (.exe)
        uses: actions/upload-artifact@v4
        with:
          name: Actual-Windows-x64-Installer
          path: packages/desktop-electron/dist/Actual-windows-x64.exe
          if-no-files-found: error

      - name: Upload Windows x64 Appx
        uses: actions/upload-artifact@v4
        with:
          name: Actual-Windows-x64-Appx
          path: packages/desktop-electron/dist/Actual-windows-x64.appx
          if-no-files-found: error
